-- Rope & Rung crew database — Cloudflare D1 (SQLite).
-- Replaces supabase/schema.sql, whose project no longer exists (2026-09-14).
--
-- Same trust model, enforced in a different place. D1 has no roles and no RLS:
-- nothing but the Worker (worker/src/index.js) can reach this database at all,
-- so the Worker IS the security-definer layer. Every procedure there re-checks
-- the crew code against the crew id — and against the profile or set being
-- touched — before it reads or writes a row, exactly as the Postgres functions
-- did. The code is the only credential this app has; it is generated by the
-- Worker from crypto.getRandomValues and never chosen by a human.
--
-- Apply:  npx wrangler d1 execute rope-and-rung --remote --file=worker/schema.sql

CREATE TABLE IF NOT EXISTS crews (
  id         TEXT PRIMARY KEY,
  name       TEXT NOT NULL DEFAULT 'The Climb',
  crew_code  TEXT NOT NULL UNIQUE
             CHECK (length(crew_code) = 8 AND crew_code NOT GLOB '*[^ABCDEFGHJKLMNPQRSTUVWXYZ23456789]*'),
  settings   TEXT NOT NULL DEFAULT '{}',          -- JSON
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS profiles (
  id         TEXT PRIMARY KEY,
  crew_id    TEXT NOT NULL REFERENCES crews(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  avatar     TEXT NOT NULL DEFAULT '💪',
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS profiles_crew ON profiles (crew_id);

CREATE TABLE IF NOT EXISTS sets (
  id         TEXT PRIMARY KEY,
  profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  day        TEXT NOT NULL,                        -- YYYY-MM-DD
  reps       INTEGER NOT NULL CHECK (reps <> 0 AND reps >= -500 AND reps <= 500),
  logged_at  TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS sets_profile_day ON sets (profile_id, day);

CREATE TABLE IF NOT EXISTS day_status (
  id          TEXT PRIMARY KEY,
  profile_id  TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  day         TEXT NOT NULL,
  kind        TEXT NOT NULL CHECK (kind IN ('rest', 'excuse')),
  excuse_text TEXT,
  created_at  TEXT NOT NULL,
  UNIQUE (profile_id, day, kind)
);
